language: java
jdk: openjdk12

services:
  - docker

cache:
  directories:
    - $HOME/.m2

after_script:
  - docker build -t konrader/unifi-cloud-exporter .
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker push konrader/unifi-cloud-exporter
